
package com.knight.estoque.servico.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ListagemLivros", targetNamespace = "http://servico.estoque.knight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemLivros {


    /**
     * 
     * @return
     *     returns java.util.List<com.knight.estoque.servico.client.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://servico.estoque.knight.com/", className = "com.knight.estoque.servico.client.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://servico.estoque.knight.com/", className = "com.knight.estoque.servico.client.ListarLivrosResponse")
    public List<Livro> listarLivros();

    /**
     * 
     * @param numeroDaPagina
     * @param tamanhoDaPagina
     * @return
     *     returns java.util.List<com.knight.estoque.servico.client.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivrosPaginacao", targetNamespace = "http://servico.estoque.knight.com/", className = "com.knight.estoque.servico.client.ListarLivrosPaginacao")
    @ResponseWrapper(localName = "listarLivrosPaginacaoResponse", targetNamespace = "http://servico.estoque.knight.com/", className = "com.knight.estoque.servico.client.ListarLivrosPaginacaoResponse")
    public List<Livro> listarLivrosPaginacao(
        @WebParam(name = "numeroDaPagina", targetNamespace = "")
        int numeroDaPagina,
        @WebParam(name = "tamanhoDaPagina", targetNamespace = "")
        int tamanhoDaPagina);

}
