
package com.knight.estoque.servico.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ListagemLivrosService", targetNamespace = "http://servico.estoque.knight.com/", wsdlLocation = "http://localhost:8080/livros?wsdl")
public class ListagemLivrosService
    extends Service
{

    private final static URL LISTAGEMLIVROSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.knight.estoque.servico.client.ListagemLivrosService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.knight.estoque.servico.client.ListagemLivrosService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/livros?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/livros?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LISTAGEMLIVROSSERVICE_WSDL_LOCATION = url;
    }

    public ListagemLivrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemLivrosService() {
        super(LISTAGEMLIVROSSERVICE_WSDL_LOCATION, new QName("http://servico.estoque.knight.com/", "ListagemLivrosService"));
    }

    /**
     * 
     * @return
     *     returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort() {
        return super.getPort(new QName("http://servico.estoque.knight.com/", "ListagemLivrosPort"), ListagemLivros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.estoque.knight.com/", "ListagemLivrosPort"), ListagemLivros.class, features);
    }

}
